"""
VaultMind Forge - Engine Structure Builder
Adapted from Comprehensive_Ai_Filter/deploy_asset_converter.py

Creates engine-specific directory structures for asset export.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Dict, List, Optional, Any
import json


class EngineStructureBuilder:
    """
    Creates optimized directory structures for game engines.
    Adapted for VaultMind Forge asset pipeline.
    """

    def __init__(
        self,
        base_path: Optional[Path] = None,
        logger: Optional[logging.Logger] = None
    ):
        """
        Initialize structure builder.

        Args:
            base_path: Root assets directory (defaults to LPG/assets)
            logger: Optional logger instance
        """
        if base_path is None:
            # Default to VaultMind Forge assets directory
            base_path = Path(__file__).parents[3] / "assets"

        self.base_path = Path(base_path)
        self.output_path = self.base_path / "output"
        self.logger = logger or self._setup_logger()

        # Ensure output directory exists
        self.output_path.mkdir(parents=True, exist_ok=True)

    def _setup_logger(self) -> logging.Logger:
        """Set up default logger."""
        logger = logging.getLogger("VaultMindForge.EngineStructureBuilder")
        logger.setLevel(logging.INFO)

        if not logger.handlers:
            handler = logging.StreamHandler()
            handler.setLevel(logging.INFO)
            formatter = logging.Formatter(
                '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
            )
            handler.setFormatter(formatter)
            logger.addHandler(handler)

        return logger

    def _create_directory_structure(
        self,
        base: Path,
        structure: Dict[str, Any]
    ) -> None:
        """
        Recursively create directory structure.

        Args:
            base: Base directory
            structure: Dictionary defining structure
        """
        for name, contents in structure.items():
            current_path = base / name

            # Create directory
            try:
                current_path.mkdir(parents=True, exist_ok=True)
                self.logger.debug(f"Created directory: {current_path}")
            except Exception as e:
                self.logger.error(f"Error creating directory {current_path}: {e}")
                continue

            # Handle contents
            if isinstance(contents, list):
                # List of subdirectories
                for item in contents:
                    subdir = current_path / item
                    subdir.mkdir(parents=True, exist_ok=True)
                    self.logger.debug(f"Created subdirectory: {subdir}")

            elif isinstance(contents, dict):
                # Nested structure
                self._create_directory_structure(current_path, contents)

    def _create_readme(
        self,
        path: Path,
        engine_name: str,
        description: str,
        conventions: List[str]
    ) -> None:
        """
        Create README file for engine directory.

        Args:
            path: Directory path
            engine_name: Engine name
            description: Engine description
            conventions: List of naming/format conventions
        """
        readme_path = path / "README.md"

        content = f"""# {engine_name} Assets

## Description
{description}

## Directory Structure
```
{path.name}/
├── models/      # 3D models
├── textures/    # Textures
├── materials/   # Materials
└── ...
```

## Conventions
{chr(10).join(f'- {conv}' for conv in conventions)}

## Generated by VaultMind Forge
This structure was automatically created by forge_converter.
"""

        with open(readme_path, 'w', encoding='utf-8') as f:
            f.write(content)

        self.logger.debug(f"Created README: {readme_path}")

    # ========================================================================
    # Unity Structure
    # ========================================================================

    def create_unity_structure(self, project_name: str = "UnityAssets") -> Path:
        """
        Create Unity-optimized directory structure.

        Args:
            project_name: Project name for this asset pack

        Returns:
            Path to created Unity directory
        """
        unity_path = self.output_path / "unity" / project_name

        structure = {
            "models": [],  # FBX models
            "textures": [
                "diffuse",      # BC7 compressed
                "normal",       # BC5 compressed
                "metallic",     # BC4 compressed
                "roughness",    # BC4 compressed
                "ao"            # BC4 compressed
            ],
            "materials": [],    # .mat files
            "prefabs": [],      # .prefab files
            "animations": [],   # Animation clips
            "shaders": []       # Custom shaders
        }

        self._create_directory_structure(unity_path, structure)

        conventions = [
            "Model format: FBX (2020)",
            "Texture compression: BC7 (diffuse), BC5 (normal), BC4 (single-channel)",
            "Max texture size: 2048x2048",
            "Naming: PascalCase",
            "LOD naming: ModelName_LOD0.fbx, ModelName_LOD1.fbx"
        ]

        self._create_readme(unity_path, "Unity", "Unity game engine assets", conventions)

        # Create .gitkeep files
        for subdir in unity_path.rglob('*'):
            if subdir.is_dir() and not any(subdir.iterdir()):
                (subdir / ".gitkeep").touch()

        self.logger.info(f"[OK] Created Unity structure: {unity_path}")
        return unity_path

    # ========================================================================
    # Unreal Structure
    # ========================================================================

    def create_unreal_structure(self, project_name: str = "UnrealAssets") -> Path:
        """
        Create Unreal Engine-optimized directory structure.

        Args:
            project_name: Project name for this asset pack

        Returns:
            Path to created Unreal directory
        """
        unreal_path = self.output_path / "unreal" / project_name

        structure = {
            "models": [
                "static_meshes",    # SM_ prefix
                "skeletal_meshes"   # SK_ prefix
            ],
            "textures": [
                "base_color",       # T_{name}_D
                "normal",           # T_{name}_N
                "orm",              # T_{name}_ORM (packed)
                "emissive"          # T_{name}_E
            ],
            "materials": [],        # M_{name}.uasset
            "blueprints": [],       # BP_{name}.uasset
            "animations": [],       # Animation sequences
            "particles": []         # Particle systems
        }

        self._create_directory_structure(unreal_path, structure)

        conventions = [
            "Model format: FBX (2020)",
            "Texture format: TGA",
            "Naming: Unreal prefix system (SM_, SK_, T_, M_, BP_)",
            "Packed textures: ORM (Occlusion, Roughness, Metallic)",
            "LOD naming: StaticMesh_LOD0, StaticMesh_LOD1",
            "Nanite support: Enable for high-poly static meshes"
        ]

        self._create_readme(unreal_path, "Unreal Engine", "Unreal Engine 5 assets", conventions)

        # Create .gitkeep files
        for subdir in unreal_path.rglob('*'):
            if subdir.is_dir() and not any(subdir.iterdir()):
                (subdir / ".gitkeep").touch()

        self.logger.info(f"[OK] Created Unreal structure: {unreal_path}")
        return unreal_path

    # ========================================================================
    # Godot Structure
    # ========================================================================

    def create_godot_structure(self, project_name: str = "GodotAssets") -> Path:
        """
        Create Godot-optimized directory structure.

        Args:
            project_name: Project name for this asset pack

        Returns:
            Path to created Godot directory
        """
        godot_path = self.output_path / "godot" / project_name

        structure = {
            "models": [],           # GLTF/GLB files
            "textures": [
                "diffuse",
                "normal",
                "orm",              # Packed textures
                "emission"
            ],
            "materials": [],        # .tres files
            "scenes": [],           # .tscn files
            "scripts": [],          # .gd files
            "shaders": []           # .gdshader files
        }

        self._create_directory_structure(godot_path, structure)

        conventions = [
            "Model format: GLTF/GLB (preferred)",
            "Texture format: WebP (Godot 4.x), PNG (Godot 3.x)",
            "Material format: .tres",
            "Compression: BPTC (desktop), ETC2 (mobile)",
            "Naming: snake_case"
        ]

        self._create_readme(godot_path, "Godot Engine", "Godot 4.x game engine assets", conventions)

        # Create .gitkeep files
        for subdir in godot_path.rglob('*'):
            if subdir.is_dir() and not any(subdir.iterdir()):
                (subdir / ".gitkeep").touch()

        self.logger.info(f"[OK] Created Godot structure: {godot_path}")
        return godot_path

    # ========================================================================
    # Web/Three.js Structure
    # ========================================================================

    def create_web_structure(self, project_name: str = "WebAssets") -> Path:
        """
        Create Web/Three.js-optimized directory structure.

        Args:
            project_name: Project name for this asset pack

        Returns:
            Path to created Web directory
        """
        web_path = self.output_path / "web" / project_name

        structure = {
            "models": [
                "glb",              # Binary GLTF
                "draco"             # Draco compressed
            ],
            "textures": [
                "1024",             # Desktop
                "512",              # Tablet
                "256"               # Mobile
            ],
            "materials": [],        # Three.js JSON
            "basis": [],            # Basis Universal
            "scripts": []           # Three.js loaders
        }

        self._create_directory_structure(web_path, structure)

        conventions = [
            "Model format: GLB with Draco compression",
            "Texture formats: JPG (diffuse), PNG (normal/data)",
            "Max texture size: 1024x1024 (mobile), 2048x2048 (desktop)",
            "Max triangles: 50k per model",
            "Multiple texture sizes for responsive loading",
            "Basis Universal for cross-platform support"
        ]

        self._create_readme(web_path, "Web/Three.js", "Three.js web assets", conventions)

        # Create .gitkeep files
        for subdir in web_path.rglob('*'):
            if subdir.is_dir() and not any(subdir.iterdir()):
                (subdir / ".gitkeep").touch()

        self.logger.info(f"[OK] Created Web structure: {web_path}")
        return web_path

    # ========================================================================
    # Blender Structure
    # ========================================================================

    def create_blender_structure(self, project_name: str = "BlenderAssets") -> Path:
        """
        Create Blender-optimized directory structure.

        Args:
            project_name: Project name for this asset pack

        Returns:
            Path to created Blender directory
        """
        blender_path = self.output_path / "blender" / project_name

        structure = {
            "models": [],           # .blend files
            "textures": [
                "png",              # LDR textures
                "exr"               # HDR textures
            ],
            "materials": [],        # Embedded in .blend
            "scenes": [],           # Scene files
            "libraries": [],        # Linked libraries
            "scripts": []           # Python scripts
        }

        self._create_directory_structure(blender_path, structure)

        conventions = [
            "Native format: .blend",
            "Texture formats: PNG (LDR), EXR (HDR)",
            "Purpose: Intermediate editing and re-export",
            "Use asset libraries for reusable components"
        ]

        self._create_readme(blender_path, "Blender", "Blender 3D assets", conventions)

        # Create .gitkeep files
        for subdir in blender_path.rglob('*'):
            if subdir.is_dir() and not any(subdir.iterdir()):
                (subdir / ".gitkeep").touch()

        self.logger.info(f"[OK] Created Blender structure: {blender_path}")
        return blender_path

    # ========================================================================
    # Create All Structures
    # ========================================================================

    def create_all_structures(self, project_name: str = "MultiPlatform") -> Dict[str, Path]:
        """
        Create directory structures for all supported engines.

        Args:
            project_name: Base project name

        Returns:
            Dictionary mapping engine name to created path
        """
        self.logger.info(f"Creating multi-platform structure: {project_name}")

        structures = {
            "unity": self.create_unity_structure(project_name),
            "unreal": self.create_unreal_structure(project_name),
            "godot": self.create_godot_structure(project_name),
            "web": self.create_web_structure(project_name),
            "blender": self.create_blender_structure(project_name)
        }

        # Create master index
        index_path = self.output_path / f"{project_name}_index.json"
        index_data = {
            "project_name": project_name,
            "engines": {
                engine: str(path.relative_to(self.base_path))
                for engine, path in structures.items()
            },
            "created_by": "VaultMind Forge - forge_converter"
        }

        with open(index_path, 'w', encoding='utf-8') as f:
            json.dump(index_data, f, indent=2)

        self.logger.info(f"[OK] Created all engine structures")
        self.logger.info(f"  Index: {index_path}")

        return structures


# ============================================================================
# Example Usage
# ============================================================================

if __name__ == "__main__":
    # Set up logging
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )

    # Create builder
    builder = EngineStructureBuilder()

    # Create structures for all engines
    structures = builder.create_all_structures("CharacterAssets")

    print("\n[OK] Created engine structures:")
    for engine, path in structures.items():
        print(f"  {engine}: {path}")
