"""
Tests for ModelManager

Tests model loading/unloading, memory management, and thread safety.
"""

import pytest
import time
import threading
from unittest.mock import Mock, patch

from vaultmind_forge.forge_ai import (
    ModelManager,
    ModelConfig,
    ModelRole,
    ModelState,
)


# Mock model for testing (no actual GPU needed)
class MockModel:
    """Mock model for testing"""
    def __init__(self, name: str):
        self.name = name
        self.device = "cpu"

    def generate(self, *args, **kwargs):
        return f"Generated by {self.name}"


def create_mock_loader(model_name: str):
    """Create mock loader function"""
    def loader(config: ModelConfig):
        time.sleep(0.1)  # Simulate load time
        return MockModel(model_name)
    return loader


def test_model_registration():
    """Test model registration"""
    manager = ModelManager(max_total_memory_gb=24.0)

    config = ModelConfig(
        name="test-model",
        role=ModelRole.PLANNER,
        model_path="test/model",
        loader_func=create_mock_loader("test-model"),
        max_memory_gb=8.0,
    )

    manager.register_model(config)

    assert "test-model" in manager.models
    assert manager.models["test-model"].state == ModelState.UNLOADED

    manager.shutdown()


def test_model_loading():
    """Test model loading"""
    manager = ModelManager(max_total_memory_gb=24.0)

    config = ModelConfig(
        name="test-model",
        role=ModelRole.PLANNER,
        model_path="test/model",
        loader_func=create_mock_loader("test-model"),
        max_memory_gb=8.0,
    )

    manager.register_model(config)

    # Load model
    model = manager.load_model("test-model")

    assert model is not None
    assert isinstance(model, MockModel)
    assert manager.models["test-model"].state == ModelState.LOADED

    manager.shutdown()


def test_model_unloading():
    """Test model unloading"""
    manager = ModelManager(max_total_memory_gb=24.0)

    config = ModelConfig(
        name="test-model",
        role=ModelRole.PLANNER,
        model_path="test/model",
        loader_func=create_mock_loader("test-model"),
        max_memory_gb=8.0,
    )

    manager.register_model(config)
    manager.load_model("test-model")

    # Unload model
    manager.unload_model("test-model")

    assert manager.models["test-model"].state == ModelState.UNLOADED
    assert manager.models["test-model"].model_instance is None

    manager.shutdown()


def test_context_manager():
    """Test context manager usage"""
    manager = ModelManager(max_total_memory_gb=24.0)

    config = ModelConfig(
        name="test-model",
        role=ModelRole.PLANNER,
        model_path="test/model",
        loader_func=create_mock_loader("test-model"),
        max_memory_gb=8.0,
    )

    manager.register_model(config)

    # Use context manager
    with manager.use_model("test-model") as model:
        assert isinstance(model, MockModel)
        assert manager.models["test-model"].state == ModelState.LOADED

    # Model should still be loaded (not auto-unloaded)
    assert manager.models["test-model"].state == ModelState.LOADED

    manager.shutdown()


def test_memory_eviction():
    """Test priority-based memory eviction"""
    manager = ModelManager(max_total_memory_gb=15.0)  # Limited memory

    # Register two models that together exceed limit
    config1 = ModelConfig(
        name="model-1",
        role=ModelRole.PLANNER,
        model_path="test/model1",
        loader_func=create_mock_loader("model-1"),
        max_memory_gb=10.0,
        priority=5,  # Lower priority
    )

    config2 = ModelConfig(
        name="model-2",
        role=ModelRole.DIFFUSION,
        model_path="test/model2",
        loader_func=create_mock_loader("model-2"),
        max_memory_gb=10.0,
        priority=10,  # Higher priority
    )

    manager.register_model(config1)
    manager.register_model(config2)

    # Load model 1
    manager.load_model("model-1")
    assert manager.models["model-1"].state == ModelState.LOADED

    # Load model 2 (should evict model 1)
    with patch.object(manager, '_estimate_model_memory', return_value=10.0):
        manager.load_model("model-2")

    # Model 2 should be loaded
    assert manager.models["model-2"].state == ModelState.LOADED

    manager.shutdown()


def test_keep_loaded():
    """Test keep_loaded flag"""
    manager = ModelManager(max_total_memory_gb=24.0)

    config = ModelConfig(
        name="test-model",
        role=ModelRole.PLANNER,
        model_path="test/model",
        loader_func=create_mock_loader("test-model"),
        max_memory_gb=8.0,
        keep_loaded=True,
    )

    manager.register_model(config)
    manager.load_model("test-model")

    # Try to unload (should fail due to keep_loaded)
    manager.unload_model("test-model")
    assert manager.models["test-model"].state == ModelState.LOADED

    # Force unload should work
    manager.unload_model("test-model", force=True)
    assert manager.models["test-model"].state == ModelState.UNLOADED

    manager.shutdown()


def test_multiple_loads():
    """Test loading same model multiple times"""
    manager = ModelManager(max_total_memory_gb=24.0)

    config = ModelConfig(
        name="test-model",
        role=ModelRole.PLANNER,
        model_path="test/model",
        loader_func=create_mock_loader("test-model"),
        max_memory_gb=8.0,
    )

    manager.register_model(config)

    # Load multiple times
    model1 = manager.load_model("test-model")
    model2 = manager.load_model("test-model")

    # Should return same instance
    assert model1 is model2
    assert manager.models["test-model"].load_count == 1

    manager.shutdown()


def test_get_stats():
    """Test statistics gathering"""
    manager = ModelManager(max_total_memory_gb=24.0)

    config = ModelConfig(
        name="test-model",
        role=ModelRole.PLANNER,
        model_path="test/model",
        loader_func=create_mock_loader("test-model"),
        max_memory_gb=8.0,
    )

    manager.register_model(config)
    manager.load_model("test-model")

    stats = manager.get_stats()

    assert "total_memory_usage_gb" in stats
    assert "max_memory_gb" in stats
    assert "loaded_models" in stats
    assert "test-model" in stats["loaded_models"]

    manager.shutdown()


def test_thread_safety():
    """Test thread-safe concurrent access"""
    manager = ModelManager(max_total_memory_gb=24.0)

    config = ModelConfig(
        name="test-model",
        role=ModelRole.PLANNER,
        model_path="test/model",
        loader_func=create_mock_loader("test-model"),
        max_memory_gb=8.0,
    )

    manager.register_model(config)

    results = []
    errors = []

    def worker():
        try:
            with manager.use_model("test-model") as model:
                time.sleep(0.1)
                results.append(model.name)
        except Exception as e:
            errors.append(e)

    # Create multiple threads
    threads = [threading.Thread(target=worker) for _ in range(5)]

    # Start all threads
    for t in threads:
        t.start()

    # Wait for completion
    for t in threads:
        t.join()

    # Check results
    assert len(errors) == 0
    assert len(results) == 5
    assert all(r == "test-model" for r in results)

    manager.shutdown()


def test_auto_unload_disabled():
    """Test with auto-unload disabled"""
    manager = ModelManager(
        max_total_memory_gb=24.0,
        auto_unload=False,  # Disable auto-unload
    )

    config = ModelConfig(
        name="test-model",
        role=ModelRole.PLANNER,
        model_path="test/model",
        loader_func=create_mock_loader("test-model"),
        max_memory_gb=8.0,
    )

    manager.register_model(config)
    manager.load_model("test-model")

    # Wait (model should NOT auto-unload)
    time.sleep(0.5)

    assert manager.models["test-model"].state == ModelState.LOADED

    manager.shutdown()
