export const nodeCategories = [
  { id: 'all', name: 'All' },
  { id: 'input', name: 'Input' },
  { id: 'generation', name: 'Generation' },
  { id: 'ai_agent', name: 'AI Agent' },
  { id: 'enhancement', name: 'Enhancement' },
  { id: 'validation', name: 'Validation' },
  { id: 'processing', name: 'Processing' },
  { id: 'output', name: 'Output' },
  { id: 'utility', name: 'Utility' },
]

export const socketColors = {
  image: '#FF5555',
  text: '#55FF55',
  number: '#888888',
  video: '#FF8855',
  mesh_3d: '#5555FF',
  any: '#4A90E2',
}

export const nodeLibrary = [
  {
    type: 'textInput',
    name: 'Text Input',
    description: 'Enter text manually',
    category: 'input',
    icon: 'T',
    color: '#888888',
    aiControllable: false,
    pythonModule: 'forge_input.text_input',
    inputs: [],
    outputs: [{ name: 'text', type: 'text', color: '#55FF55' }],
  },
  {
    type: 'sdxlGenerator',
    name: 'SDXL Generator',
    description: 'Generate images with Stable Diffusion XL',
    category: 'generation',
    icon: 'SD',
    color: '#E91E63',
    aiControllable: true,
    pythonModule: 'forge_diffusion.sdxl_generator',
    inputs: [
      { name: 'prompt', type: 'text', required: true, color: '#55FF55' },
      { name: 'width', type: 'number', default: 1024, color: '#888888' },
    ],
    outputs: [
      { name: 'image', type: 'image', color: '#FF5555' },
    ],
  },
  {
    type: 'promptRefiner',
    name: 'Prompt Refiner',
    description: 'Enhance prompts with Merlinv1 AI',
    category: 'ai_agent',
    icon: 'AI',
    color: '#4CAF50',
    merlinv1Required: true,
    pythonModule: 'forge_agents.prompt_refiner',
    inputs: [{ name: 'prompt', type: 'text', required: true, color: '#55FF55' }],
    outputs: [{ name: 'refined_prompt', type: 'text', color: '#55FF55' }],
  },
  {
    type: 'superResolution',
    name: 'Super Resolution',
    description: 'Upscale images with AI',
    category: 'enhancement',
    icon: 'SR',
    color: '#2196F3',
    pythonModule: 'forge_sr.super_resolution',
    inputs: [
      { name: 'image', type: 'image', required: true, color: '#FF5555' },
      { name: 'scale', type: 'number', default: 2, color: '#888888' },
    ],
    outputs: [{ name: 'upscaled_image', type: 'image', color: '#FF5555' }],
  },
  // INPUT NODES (2 more)
  {
    type: 'numberInput',
    name: 'Number Input',
    description: 'Enter numeric value',
    category: 'input',
    icon: '#',
    color: '#888888',
    aiControllable: false,
    pythonModule: 'forge_input.number_input',
    inputs: [],
    outputs: [{ name: 'value', type: 'number', color: '#888888' }],
  },
  {
    type: 'imageLoader',
    name: 'Image Loader',
    description: 'Load image from file',
    category: 'input',
    icon: 'IMG',
    color: '#FF9800',
    aiControllable: false,
    pythonModule: 'forge_intake.image_loader',
    inputs: [{ name: 'path', type: 'text', required: true, color: '#55FF55' }],
    outputs: [{ name: 'image', type: 'image', color: '#FF5555' }],
  },
  {
    type: 'styleProfile',
    name: 'Style Profile',
    description: 'Load predefined style settings',
    category: 'input',
    icon: 'ST',
    color: '#9C27B0',
    aiControllable: false,
    pythonModule: 'forge_input.style_profile',
    inputs: [{ name: 'profile_name', type: 'text', required: true, color: '#55FF55' }],
    outputs: [{ name: 'style_params', type: 'any', color: '#4A90E2' }],
  },
  // GENERATION NODES (3 more)
  {
    type: 'videoGenerator',
    name: 'Video Generator',
    description: 'Generate video from images',
    category: 'generation',
    icon: 'VID',
    color: '#FF5722',
    aiControllable: true,
    pythonModule: 'forge_video.video_generator',
    inputs: [
      { name: 'images', type: 'image', required: true, color: '#FF5555' },
      { name: 'fps', type: 'number', default: 30, color: '#888888' },
    ],
    outputs: [{ name: 'video', type: 'video', color: '#FF8855' }],
  },
  {
    type: 'mesh3dGenerator',
    name: '3D Mesh Generator',
    description: 'Generate 3D mesh from text/image',
    category: 'generation',
    icon: '3D',
    color: '#3F51B5',
    aiControllable: true,
    pythonModule: 'forge_3d.mesh_generator',
    inputs: [
      { name: 'prompt', type: 'text', required: true, color: '#55FF55' },
      { name: 'reference_image', type: 'image', required: false, color: '#FF5555' },
    ],
    outputs: [{ name: 'mesh', type: 'mesh_3d', color: '#5555FF' }],
  },
  {
    type: 'proceduralGenerator',
    name: 'Procedural Generator',
    description: 'Generate procedural content',
    category: 'generation',
    icon: 'PR',
    color: '#00BCD4',
    aiControllable: true,
    pythonModule: 'forge_procedural.procedural_generator',
    inputs: [
      { name: 'seed', type: 'number', required: false, color: '#888888' },
      { name: 'type', type: 'text', required: true, color: '#55FF55' },
    ],
    outputs: [{ name: 'result', type: 'any', color: '#4A90E2' }],
  },
  // AI AGENT NODES (1 more)
  {
    type: 'parameterOptimizer',
    name: 'Parameter Optimizer',
    description: 'AI-powered parameter tuning',
    category: 'ai_agent',
    icon: 'OPT',
    color: '#4CAF50',
    aiControllable: false,
    pythonModule: 'forge_agents.parameter_optimizer',
    inputs: [
      { name: 'context', type: 'text', required: true, color: '#55FF55' },
      { name: 'target', type: 'text', required: false, color: '#55FF55' },
    ],
    outputs: [{ name: 'optimized_params', type: 'any', color: '#4A90E2' }],
  },
  // ENHANCEMENT NODES (1 more)
  {
    type: 'semanticDownrez',
    name: 'Semantic Downscale',
    description: 'Intelligent image downscaling',
    category: 'enhancement',
    icon: 'SD',
    color: '#2196F3',
    aiControllable: false,
    pythonModule: 'forge_semantic.semantic_downrezzer',
    inputs: [
      { name: 'image', type: 'image', required: true, color: '#FF5555' },
      { name: 'target_size', type: 'number', required: true, color: '#888888' },
    ],
    outputs: [{ name: 'downscaled_image', type: 'image', color: '#FF5555' }],
  },
  // VALIDATION NODES (1 more)
  {
    type: 'qualityValidator',
    name: 'Quality Validator',
    description: 'Validate and assess quality',
    category: 'validation',
    icon: 'QC',
    color: '#FF9800',
    aiControllable: false,
    pythonModule: 'forge_validator.quality_validator',
    inputs: [{ name: 'input', type: 'any', required: true, color: '#4A90E2' }],
    outputs: [
      { name: 'quality_score', type: 'number', color: '#888888' },
      { name: 'report', type: 'any', color: '#4A90E2' },
    ],
  },
  // PROCESSING NODES (2 more)
  {
    type: 'formatConverter',
    name: 'Format Converter',
    description: 'Convert between formats',
    category: 'processing',
    icon: 'CNV',
    color: '#607D8B',
    aiControllable: false,
    pythonModule: 'forge_converter.format_converter',
    inputs: [
      { name: 'input', type: 'any', required: true, color: '#4A90E2' },
      { name: 'target_format', type: 'text', required: true, color: '#55FF55' },
    ],
    outputs: [{ name: 'output', type: 'any', color: '#4A90E2' }],
  },
  {
    type: 'assetPackager',
    name: 'Asset Packager',
    description: 'Package assets for distribution',
    category: 'processing',
    icon: 'PKG',
    color: '#795548',
    aiControllable: false,
    pythonModule: 'forge_packaging.asset_packager',
    inputs: [
      { name: 'assets', type: 'any', required: true, color: '#4A90E2' },
      { name: 'format', type: 'text', required: true, color: '#55FF55' },
    ],
    outputs: [{ name: 'package', type: 'any', color: '#4A90E2' }],
  },
  // OUTPUT NODES (2 more)
  {
    type: 'saveImage',
    name: 'Save Image',
    description: 'Save image to file',
    category: 'output',
    icon: 'SAV',
    color: '#4CAF50',
    aiControllable: false,
    pythonModule: 'forge_output.save_image',
    inputs: [
      { name: 'image', type: 'image', required: true, color: '#FF5555' },
      { name: 'path', type: 'text', required: true, color: '#55FF55' },
    ],
    outputs: [{ name: 'saved_path', type: 'text', color: '#55FF55' }],
  },
  {
    type: 'lineageArchive',
    name: 'Lineage Archive',
    description: 'Archive with lineage metadata',
    category: 'output',
    icon: 'ARC',
    color: '#9E9E9E',
    aiControllable: false,
    pythonModule: 'forge_lineage.lineage_archiver',
    inputs: [
      { name: 'data', type: 'any', required: true, color: '#4A90E2' },
      { name: 'metadata', type: 'any', required: false, color: '#4A90E2' },
    ],
    outputs: [{ name: 'archive_id', type: 'text', color: '#55FF55' }],
  },
  // UTILITY NODES (3 more)
  {
    type: 'branch',
    name: 'Branch',
    description: 'Conditional execution (if/else)',
    category: 'utility',
    icon: 'IF',
    color: '#FFC107',
    aiControllable: false,
    pythonModule: 'forge_utility.branch',
    inputs: [
      { name: 'condition', type: 'any', required: true, color: '#4A90E2' },
      { name: 'true_value', type: 'any', required: true, color: '#4A90E2' },
      { name: 'false_value', type: 'any', required: true, color: '#4A90E2' },
    ],
    outputs: [{ name: 'result', type: 'any', color: '#4A90E2' }],
  },
  {
    type: 'loop',
    name: 'Loop',
    description: 'Iterate over collection',
    category: 'utility',
    icon: 'LP',
    color: '#FF5722',
    aiControllable: false,
    pythonModule: 'forge_utility.loop',
    inputs: [
      { name: 'collection', type: 'any', required: true, color: '#4A90E2' },
      { name: 'operation', type: 'text', required: true, color: '#55FF55' },
    ],
    outputs: [{ name: 'results', type: 'any', color: '#4A90E2' }],
  },
  {
    type: 'cache',
    name: 'Cache',
    description: 'Cache intermediate results',
    category: 'utility',
    icon: 'CH',
    color: '#9C27B0',
    aiControllable: false,
    pythonModule: 'forge_utility.cache',
    inputs: [
      { name: 'input', type: 'any', required: true, color: '#4A90E2' },
      { name: 'cache_key', type: 'text', required: false, color: '#55FF55' },
    ],
    outputs: [{ name: 'output', type: 'any', color: '#4A90E2' }],
  },
]
